name: radiolicencja
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  yaml: ^3.1.2
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  shared_preferences: ^2.2.2
  gpt_markdown: ^1.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.1

flutter:
  uses-material-design: true
  assets:
    - assets/topics/
    - assets/images/
    - assets/question_images/
  generate: true

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/splash_vertical.png
  android_gravity: fill
  ios_content_mode: scaleAspectFill
  web_image_mode: cover
  image_web: assets/images/splash_horizontal.png
  fullscreen: true
  android_12:
    image: assets/images/splash_vertical.png
    icon_background_color: "#FFFFFF"
